prepare:
  features:
  - Age
  - Fare
  - Sex
  - sibsp
  - Parch
  - Pclass
  - Embarked
  target: 2urvived
seed: 42
split:
  stratify: true
  test_size: 0.2
train:
  criterion: gini
  max_depth: 6
  min_samples_split: 5
  model_type: random_forest
  n_estimators: 250
